.PHONY: install_pip install_setproctitle pipes all clean
install_pip:
	sudo apt update
	sudo apt install python3-pip

install_setproctitle:
	pip3 install setproctitle

pipes:
	python3 cliserv2.py
all:
	@echo "Compilación y ejecución de la práctica"

clean:
	@echo "Limpiando..."
