server:
	CHAT_HOST=localhost CHAT_PORT=12347 python3 serv7.py
 
client:
	CHAT_HOST=localhost CHAT_PORT=12347 python3 cli7.py

all:
	@echo "Compilación y ejecución de la práctica"

clean:
	rm -f *.pyc __pycache__/*
	@echo "Limpiando..."
